# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2022322134db5403bdd40384bf020a5c"
name = "upsellr-connector"
handle = "upsellr-connector-1"
application_url = "https://app.alexandrechauvin.fr"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_metaobjects"

[auth]
redirect_urls = ["https://app.alexandrechauvin.fr/auth/callback", "https://app.alexandrechauvin.fr/auth/shopify/callback", "https://app.alexandrechauvin.fr/api/auth/callback"]

[pos]
embedded = false
