api_version = "2025-07"

[[extensions]]
name = "Spécification Technique"
handle = "productspecifications"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/BlockExtension.tsx"
target = "admin.product-details.block.render"

[[extensions.targeting.metafields]]
namespace = "specs"
key = "technical"
