api_version = "2025-07"

[[extensions]]
name = "t:block_name"
handle = "productspecifications"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/BlockExtension.tsx"
target = "admin.product-details.block.render"

[extensions.targeting.capabilities]
api_access = true
network_access = true

[[extensions.metafields]]
namespace = "specs"
key = "technical"

[[extensions.metafields_permissions]]
namespace = "specs"
key = "technical"
access = "read"
